#!/bin/bash

########## Configuration / Usage Text / Etc below ##############
SCRIPT=$(basename ${0})
REPOSITORY=$(hostname | cut -d'-' -f 1)
HOSTNAME=$(hostname)
DEFAULTSERVER="GIT SERVER CHANGE ME"
DEFAULTENVIRON="live"
DBBACKUPLOC="/var/dbbackup"
DOMAIN=$(dnsdomainname)
BASEHOSTNAME="$(hostname | cut -d'-' -f 1).${DOMAIN}"
USERNAME=$(whoami | sed 's/_admin//g')
PORT=                       # GIT SERVER PORT NUMBER - CHANGE OR LEAVE BLANK FOR DEFAULT
WEBROOT="/var/www"          # CHANGE IF DIFFERENT

USAGE=$(cat <<EOF_USAGE

USAGE: ${SCRIPT} <options>

The following options are supported:

--help                       : Displays this help message.
--branch [branch to deploy]  : Defaults to master on live sites,
                             : otherwise MUST specify.
--deployed                   : Lists information about the currently
                             : deployed tag for the current server.
--no-backup                  : Skips creating DB Backup (Not recommended)
--project [project on jira]  : Defaults to "~${USERNAME}" on development
                             : systems and MUST be specified on produc-
                             : tion systems.
--repo [name of repository]  : Defaults to "${REPOSITORY}".
--server [servername]        : Defaults to "${DEFAULTSERVER}".
--no-cc-all                  : Do NOT run 'drush cc all' after deploy
--cleanup                    : Remove files no longer in repository in
                             : the '/var/www/sites/all' and '/var/www/profile'
                             : trees only.

Default user for all git operations will be the currently logged in
user (${USERNAME}).

EOF_USAGE
)

GITCONFIG=$(cat <<EOF_GITCONFIG

You need to configure your git identity and try again.
This information is required once for identifying who is
responsible for each tag this script creates during a deploy.

Example:
$ git config --global user.name "Your Name"
$ git config --global user.email "youremail@yourdomain.com"

EOF_GITCONFIG
)

# Default to creating a DB Backup
SKIPDB=0

# Default to running drush cc all
CCALL=0

# Default to NOT cleaning up (current method)
CLEANUP=1

###### Shouldn't need to change anything below here #######
NUMARGS="$#"

# Print usage message and exit
print_usage () {
  echo "${USAGE}" >&2
}

# return given variable if not in error 
assign_value () {
  case ${1} in
    --*)
      print_usage
      exit 4
      ;;
    *)
      echo ${1}
      ;;
  esac
}

# Function to display the deployed version of the site
# Along with other relevant information. 
display_deployed () {
  DEPLOYED=$(sed -n '/START DEPLOY INFO/,/END DEPLOY INFO/p' ${WEBROOT}/.htaccess | tr -d [:space:])
  if [ x${DEPLOYED} != "x" ]; then
    IFS=$'#'
    set ${DEPLOYED}

    DEPINFO=$(cat <<EOF_DEPLOY
Current Deploy Information for this server:

     Deploying user: ${4}
     Drupal Version: ${7}.x
        Environment: ${5}
       Tag Deployed: ${5}-${6}
    Branch Deployed: ${8}
         Repository: ${9}
      Stash Project: ${10}

EOF_DEPLOY
)
  else
    DEPINFO="Sorry, no information yet available."
  fi

  echo -e "${DEPINFO}\n\n"
  exit
}

# parse the command line
# for each command line argument that requires
# a second parameter, assign "BAD" if it's empty
# or begins with -- (ie picking another argument)
while [ "${1}" != "" ]; do
  case ${1} in
    --no-backup)
      SKIPDB=1
      shift 1
      ;;
    --branch)
      BRANCH=$(assign_value ${2})
      shift 2
      ;;
    --deployed)
      display_deployed
      ;;
    --project)
      PROJ=$(assign_value ${2})
      shift 2
      ;;
    --repo)
      REPO=$(assign_value ${2})
      shift 2
      ;;
    --server)
      if [ x"${SERVER}" == "x" ]; then
        SERVER=${USERNAME}"@"$(assign_value ${2})
      fi
      shift 2
      ;;
    --no-cc-all)
      CCALL=1
      shift 1
      ;;
    --cleanup)
      CLEANUP=0
      shift 1
      ;;
    --help|--*)
      print_usage
      exit 0
      ;;
  esac
done

if [ "${REPO}" == "" ]; then
  if [[ "${HOSTNAME}" =~ "-" ]]; then
    REPO=$(hostname | cut -d'-' -f 1)
  else
    REPO="${HOSTNAME}"
  fi
fi

if [[ "${HOSTNAME}" =~ "-" ]]; then
  ENVIRON=$(hostname | cut -d'-' -f 2)
else
  ENVIRON="${DEFAULTENVIRON}"
fi

if [ "${SERVER}" == "" ]; then
  SERVER="${USERNAME}@${DEFAULTSERVER}"
fi

if [ "${PROJ}" == "" ]; then
  if [ "${ENVIRON}" != "${DEFAULTENVIRON}" ]; then
    PROJ="~${USERNAME}"
  else
    echo "Must specify --project switch in live environment"
    exit
  fi
fi

if [ "${BRANCH}" == "" ]; then
  if [ "${ENVIRON}" != "${DEFAULTENVIRON}" ]; then
    print_usage
    exit 3
  else
    BRANCH="master";
  fi
fi

# We need arguments!
if [ ${NUMARGS} -le 1 ]; then
  print_usage
  exit 2
fi

if [ ! -e "${HOME}/.gitconfig" ]; then
  echo "${GITCONFIG}" >&2;
  exit 1;
fi

if [ -d /tmp/clone ]; then
  echo "Removing existing clone directory..."
  sudo rm -rf /tmp/clone
fi

GITURL="git+ssh://${SERVER}:${PORT}/${PROJ}/${REPO}.git"

echo "Cloning ${BRANCH}..."
mkdir /tmp/clone

git clone -b ${BRANCH} ${GITURL} /tmp/clone

cd /tmp/clone

TAG=$(date +%Y-%m-%d-%H-%M)
HASH=$(git log "${BRANCH}" -n 1 --pretty=format:%h)

echo "Tagging local clone..."
git tag -a -m "${BRANCH} ${HASH} to ${ENVIRON} by ${USERNAME}" "${ENVIRON}-${TAG}"

echo "Pushing tag to origin..."
git push origin "${ENVIRON}-${TAG}"

echo "Determining Drupal version..."
DVERS=$(drush status | sed -e "s/ *//g;" | grep 'Drupalversion' | cut --delimiter=: -f2 | cut --delimiter=. -f1)

if [ -r /opt/patches/D${DVERS}-ssl.patch ]; then
  echo "Patching Drupal ${DVERS}.x core to support SSL database connection..."

  # Apply Drupal ${DVERS} patch to source
  patch -d /tmp/clone -p1 < /opt/patches/D${DVERS}-ssl.patch
elif [ "${DVERS}" == "7" ]; then
  # Find the settings file for site
  SETTINGSFILE=$(sudo find ${WEBROOT} -type f -name settings.php 2> /dev/null)

  if [ "${SETTINGSFILE}" == "" ]; then
    echo "Could not find a settings.php file, please correct and try again!"
    exit 3
  fi

  echo "Checking Drupal ${DVERS}.x ${SETTINGSFILE} for previously applied patch..."

  # Look for the patch
  PATCHED=$(sudo grep -A 15 "^\$databases" ${SETTINGSFILE} | grep "'pdo'")

  # was it found?
  if [ "${PATCHED}" == "" ]; then
    # Nope
    echo "${SETTINGSFILE} not previously patched, patching..."

    # Define the SSL options for PDO connection
    PDOOPTIONS=$(cat << EOF
  'pdo' => array ( PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/mariadb/ca.crt', PDO::MYSQL_ATTR_SSL_CERT => '/etc/ssl/mariadb/${HOSTNAME}.${DOMAIN}.crt', PDO::MYSQL_ATTR_SSL_KEY => '/etc/ssl/mariadb/${HOSTNAME}.${DOMAIN}.key', ),
EOF
)

    # Find the location in file to insert PDO SSL options
    INSERTPOS=$(( $(grep -A0 -B0 -n1 "^\$databases" ${SETTINGSFILE} | cut -d: -f1) + 1 ))

    # Patch the file
    sudo sed -i "${INSERTPOS}i${PDOOPTIONS}" ${SETTINGSFILE}
  else
    # Already patched
    echo "${SETTINGSFILE} already patched, skipping..."
  fi
else
  # We have an unsupported install, Red Flag!!
  echo "Error: No patch found for Drupal ${DVERS}.x!"
  echo "Processing aborted!"
  echo "EXAMINE SOURCE in /tmp/clone!!"
  exit 2
fi

if [ ${SKIPDB} -eq 0 ]; then
  echo "Removing old backup DB files..."
  GARBAGE=$(sudo find ${DBBACKUPLOC}/* -mtime +1 -delete 2&>1)

  echo "Creating/Compressing (bzip2) DB Backup..."
  cd ${WEBROOT}
  drush sql-dump | bzip2 > ${DBBACKUPLOC}/${ENVIRON}-${TAG}.sql.bz2
else
  echo "Skipped DB Backup..."
fi

echo "Configuring permissions..."
if [ "${ENVIRON}" == "live" ]; then
  sudo chown -R www-data:www-data /tmp/clone
else
  USER=$(whoami)
  sudo chown -R ${USER}:www-data /tmp/clone
fi

# Set permissions and sync
sudo chmod -R a-srwx /tmp/clone
sudo chmod -R ug+rX,g+w /tmp/clone

for D in `find /tmp/clone -type d`; do
  sudo chmod g+s ${D}
done

# Should we try to cleanup, and remove files not within
# this deploy (ie. removed from repository)?
if [ ${CLEANUP} -eq 0 ]; then
  # our list of excluded items.
  EXCLUDE='-x "libraries" -x "files" -x "lost+found" -x "10.18.20.*" -x "settings.php*" -x "preview" -x "*.'${DOMAIN}'" -x ".gitignore" -x ".git" -x ".ht*"'

  # For now, this just displays the files that would be deleted, doesn't actually delete them.
  FILES=$(eval "sudo diff -r ${EXCLUDE} /tmp/clone ${WEBROOT} | sed '/Binary files/d; s/://g' | grep -v '/tmp/clone' | awk '{print \$3 \"/\" \$4}'")

  # Once devs are satisfied the above list of files is correct, we ca enable the actual removal of files in the
  # following code to do the actual deletions.
  echo "Would remove the following files/directories:"

  # save the current IFS and define the new one as newline
  IFSSAVE=${IFS}
  IFS=$'\n'

  # Loop through the files/directories and delete them
  for F in ${FILES}; do
    echo "rm -rf ${F}"
  done

  # restore IFS
  IFS=${IFSSAVE}
else
  echo "Skipping cleanup of old files..."
fi

echo "Syncing ${BRANCH} to ${WEBROOT}..."
sudo rsync --super --chmod=Dg+s,ug+rw,Dug+X -rogl --exclude="private" --exclude=".git" --exclude=".gitignore" /tmp/clone/ ${WEBROOT}/

# Just so we don't throw errors below when bash can't find the /tmp/clone directory
cd ${HOME}

echo "Removing clone directory..."
sudo rm -rf /tmp/clone

# Build a deploy Description block to place at the end of the .htaccess file
DEPLOY="## START DEPLOY INFO
# ${USERNAME}
# ${ENVIRON}
# ${TAG}
# ${DVERS}
# ${BRANCH}
# ${REPOSITORY}
# ${PROJ}
## END DEPLOY INFO
"

# Remove the previous DEPLOY INFO
sudo sed -i '/START DEPLOY INFO/,/END DEPLOY INFO/d' ${WEBROOT}/.htaccess

# add the info to the end of the .htaccess file
echo -e "${DEPLOY}" | sudo tee -a ${WEBROOT}/.htaccess >/dev/null

# Find all .htaccess files and build include for apache
HTACCESS=$(find {${WEBROOT},/var/private,/var/mailinglist,/var/private_files} -name .htaccess 2>/dev/null)

# Loop through the found files and create the include file for apache
HTINCLUDE=""
for F in ${HTACCESS}; do
  DIR=$(dirname "${F}")
  HTINCLUDE+=$(printf "<Directory %s>\\\n  Include %s\\\n</Directory>\\\n" "${DIR}" "${F}")
done

# write the file
echo -e "${HTINCLUDE}" | sudo tee /etc/apache2/htaccess.d/htaccess.conf >/dev/null
sudo chmod 0644 /etc/apache2/htaccess.d/htaccess.conf

# reload apache (gracefully) to load newly created file
echo "Reloading apache..."
sudo apache2ctl graceful 2>/dev/null >/dev/null

if [ ${CCALL} -eq 0 ]; then
  echo "Cleaning site cache..."
  GARBAGE=$(echo "flush_all" | nc localhost 11211; drush cc all;)
else
  echo "Skipped clearing site cache..."
fi

echo "Launch complete!"
echo "Template for pasting to a related issue:"
echo "Deployed ${HASH} with tag ${ENVIRON}-${TAG}. - ${PROJ^^}/${REPO^^}"
echo
